version: "3.8"

services: 

  docsify-served:
    image: loclhost:3000/docsify-served
    build:
      context: .
      dockerfile: ./lts-alpine/Dockerfile
    working_dir: /var/www
    ports: 
      - 3000:3000/tcp
    volumes: 
      - ${PWD}/docs:/var/www
